apiVersion: apps/v1
kind: Deployment
metadata:
 name: user-api
spec:
 replicas: 1
 template:
  spec:
   serviceAccountName: user-api
   containers:
    - name: user-api
      command: ["/bin/sh","-c", "java -jar -Duser.timezone=Asia/Seoul -Dspring.profiles.active=dev user-api.jar"]
