apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yaml
resources:
- ../base
images:
- name: user-api-image
  newName: <iam account number>.dkr.ecr.ap-northeast-2.amazonaws.com/dev-user-api
  newTag: "276"
